### ISSUE TITLE
cannot read property of toLowerCase of undefined

### ISSUE THREAD

**Issue by ChristianSch** [andinfinity/idrop.link-backend#40]
```
2015-06-20T21:09:46.467544+00:00 app[web.1]: /app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:108
2015-06-20T21:09:46.467555+00:00 app[web.1]:     at EventEmitter.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:45)
2015-06-20T21:09:46.467549+00:00 app[web.1]:   if (this.ended && !this.hasRejectListeners()) throw reason;
2015-06-20T21:09:46.467563+00:00 app[web.1]:     at Promise.resolve (/app/node_modules/mongoose/lib/promise.js:113:23)
2015-06-20T21:09:46.467551+00:00 app[web.1]:                                                       ^
2015-06-20T21:09:46.467560+00:00 app[web.1]:     at Promise.safeEmit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
2015-06-20T21:09:46.467569+00:00 app[web.1]:     at EventEmitter.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:45)
2015-06-20T21:09:46.467552+00:00 app[web.1]: TypeError: Cannot read property 'toLowerCase' of undefined
2015-06-20T21:09:46.467562+00:00 app[web.1]:     at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
2015-06-20T21:09:46.467565+00:00 app[web.1]:     at model.<anonymous> (/app/node_modules/mongoose/lib/document.js:1561:39)
2015-06-20T21:09:46.467553+00:00 app[web.1]:     at EventEmitter.<anonymous> (/app/frontend/index.js:85:50)
2015-06-20T21:09:46.467572+00:00 app[web.1]:     at Promise.safeEmit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
2015-06-20T21:09:46.467557+00:00 app[web.1]:     at EventEmitter.emit (events.js:110:17)
2015-06-20T21:09:46.467566+00:00 app[web.1]:     at next_ (/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:89:34)
2015-06-20T21:09:46.467568+00:00 app[web.1]:     at EventEmitter.fnWrapper (/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:171:15)
2015-06-20T21:09:46.467571+00:00 app[web.1]:     at EventEmitter.emit (events.js:110:17)
2015-06-20T21:09:46.467574+00:00 app[web.1]:     at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
2015-06-20T21:09:46.467578+00:00 app[web.1]:     at process._tickDomainCallback (node.js:381:11)
2015-06-20T21:09:46.467575+00:00 app[web.1]:     at p1.then.then.self.isNew (/app/node_modules/mongoose/lib/model.js:254:27)
2015-06-20T21:09:46.467577+00:00 app[web.1]:     at newTickHandler (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:229:18)
2015-06-20T21:09:46.701664+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/api/v1/users/555f75402105f60300b8feb5/drops/5585d67f07915103005b91d5" host=idrop.link request_id=a593332b-a178-4a7e-9380-78e9e7e9d311 fwd="95.211.186.214" dyno=web.1 connect=3ms service=26976ms status=503 bytes=0
2015-06-20T21:09:46.699614+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/d/VJw-gsSaAI" host=idrop.link request_id=b0bcba4d-6b40-4cdc-b801-9a9166427923 fwd="46.5.2.87" dyno=web.1 connect=1ms service=392ms status=503 bytes=0
2015-06-20T21:09:47.789326+00:00 heroku[web.1]: State changed from up to crashed
2015-06-20T21:09:47.790348+00:00 heroku[web.1]: State changed from crashed to starting
2015-06-20T21:09:47.774718+00:00 heroku[web.1]: Process exited with status 1
2015-06-20T21:09:50.958906+00:00 heroku[web.1]: Starting process with command `node index.js`
2015-06-20T21:09:52.770813+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-06-20T21:09:52.770845+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-06-20T21:09:53.870719+00:00 app[web.1]: Listening at localhost:49154
2015-06-20T21:09:54.488546+00:00 heroku[web.1]: State changed from starting to up
2015-06-20T21:09:54.415942+00:00 app[web.1]: Mongoose connected to database
2015-06-20T21:09:55.436759+00:00 app[web.1]: /app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:108
2015-06-20T21:09:55.436765+00:00 app[web.1]:   if (this.ended && !this.hasRejectListeners()) throw reason;
2015-06-20T21:09:55.436767+00:00 app[web.1]:                                                       ^
2015-06-20T21:09:55.436773+00:00 app[web.1]:     at EventEmitter.emit (events.js:110:17)
2015-06-20T21:09:55.436769+00:00 app[web.1]: TypeError: Cannot read property 'toLowerCase' of undefined
2015-06-20T21:09:55.436775+00:00 app[web.1]:     at Promise.safeEmit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
2015-06-20T21:09:55.436770+00:00 app[web.1]:     at EventEmitter.<anonymous> (/app/frontend/index.js:85:50)
2015-06-20T21:09:55.436772+00:00 app[web.1]:     at EventEmitter.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.j
s:175:45)
2015-06-20T21:09:55.436778+00:00 app[web.1]:     at Promise.resolve (/app/node_modules/mongoose/lib/promise.js:113:23)
2015-06-20T21:09:55.436777+00:00 app[web.1]:     at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
2015-06-20T21:09:55.436779+00:00 app[web.1]:     at model.<anonymous> (/app/node_modules/mongoose/lib/document.js:1561:39)
2015-06-20T21:09:55.436782+00:00 app[web.1]:     at EventEmitter.fnWrapper (/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:171:15)
2015-06-20T21:09:55.436785+00:00 app[web.1]:     at EventEmitter.emit (events.js:110:17)
2015-06-20T21:09:55.436781+00:00 app[web.1]:     at next_ (/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:89:34)
2015-06-20T21:09:55.436797+00:00 app[web.1]:     at newTickHandler (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:229:18)
2015-06-20T21:09:55.436784+00:00 app[web.1]:     at EventEmitter.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:45)
2015-06-20T21:09:55.436787+00:00 app[web.1]:     at Promise.safeEmit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
2015-06-20T21:09:55.436795+00:00 app[web.1]:     at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
2015-06-20T21:09:55.436796+00:00 app[web.1]:     at p1.then.then.self.isNew (/app/node_modules/mongoose/lib/model.js:254:27)
2015-06-20T21:09:55.436799+00:00 app[web.1]:     at process._tickDomainCallback (node.js:381:11)
2015-06-20T21:09:55.482849+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/d/VJw-gsSaAI" host=idrop.link request_id=b6b3536e-bba0-4303-91d6-9bdf2d376608 fwd="95.211.186.214" dyno=web.1 connect=3ms service=172ms status=503 bytes=0
2015-06-20T21:09:56.314555+00:00 heroku[web.1]: State changed from up to crashed
2015-06-20T21:09:56.296658+00:00 heroku[web.1]: Process exited with status 1
2015-06-20T21:12:03.222640+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=idrop.link request_id=ea8d92e4-4310-48cc-a59c-f66be0dab106 fwd="95.211.186.214" dyno= connect= service= status=503 bytes=
```

**Comment by ChristianSch** [comment]
It seems to be caused by heroic terminating the app after 30 minutes of no requests (which is common in the free tier):
```
2015-06-21T18:52:23.276859+00:00 heroku[router]: at=info method=GET path="/public/img/background.jpg" host=idrop.link request_id=72159d24-2099-4d30-b404-ff7553ffe1da fwd="46.5.2.87" dyno=web.1 connect=2ms service=12ms status=304 bytes=347
2015-06-21T19:54:41.273504+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2015-06-21T19:54:44.409764+00:00 heroku[web.1]: Process exited with status 143
2015-06-21T19:54:36.425338+00:00 heroku[web.1]: Idling
2015-06-21T19:54:36.425815+00:00 heroku[web.1]: State changed from up to down
2015-06-23T02:32:33.570760+00:00 heroku[router]: 
at=error code=H10 desc="App crashed" method=GET path="/" host=www.idrop.link request_id=3db9bfae-9e76-444a-bbc7-068458cc2989 fwd="52.0.89.236" dyno= connect= service= status=503 bytes=
```

The first entry looks ok, then the app is terminated. The next request results in an error.

**Comment by ChristianSch** [comment]
I can't reproduce this right now. Is it resolved? We should watch this!
